<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit94b9a4d62453b249117e73586a6d2f51
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit94b9a4d62453b249117e73586a6d2f51::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit94b9a4d62453b249117e73586a6d2f51::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit94b9a4d62453b249117e73586a6d2f51::$classMap;

        }, null, ClassLoader::class);
    }
}
